Update compiler and reduce final image size
jeandeaual/mplabx-xc8-build-action pull request #1
Opened 2021-06-03 15:43 UTC by usimd

GitHub actions failed with errors indicating no space was left on the drive. This PR runs will clean apt resources after installation and only install IDE components for 8bit MCUs. In addition, XC8 is updated to 2.20.

Locally, this resulted in an image size of ~5.5GB compared to ~10GB before the change.

2021-06-07 06:40 UTC, jeandeaual commented
Thanks, that looks great!
Just one thing: can you keep the XC8 version to 1.34 in this PR? I have a project that needs this specific version.
I'll try to make it customizable in another PR.

2021-06-07 06:41 UTC, jeandeaual commented on README.md
> +* [XC8](https://www.microchip.com/en-us/development-tools-tools-and-software/mplab-xc-compilers) v2.20
```suggestion
* [XC8](https://www.microchip.com/en-us/development-tools-tools-and-software/mplab-xc-compilers) v1.34
```

2021-06-07 06:41 UTC, jeandeaual requested changes

2021-06-07 06:41 UTC, jeandeaual commented on build.sh
> +echo "Building project $1:$2 with MPLAB X v5.45 and XC8 v2.20"
```suggestion
echo "Building project $1:$2 with MPLAB X v5.45 and XC8 v1.34"
```

2021-06-07 06:41 UTC, jeandeaual commented on Dockerfile
> +ARG XC8_VERSION=2.20
```suggestion
ARG XC8_VERSION=1.34
```

2021-06-07 17:47 UTC, usimd commented
Setting the versions externally as params would be awesome :smile:

2021-06-08 11:51 UTC, jeandeaual approved these changes

2021-06-08 11:52 UTC, merged

2021-06-08 11:58 UTC, jeandeaual commented
@usimd Thanks again for the PR!
I just released your changes as `jeandeaual/mplabx-xc8-build-action@v0.2.0` and you can follow #2 regarding setting the XC8 version as a parameter.